Repository KhronosGroup/SYCL-Docs, pull requests merged in 2019-08, with the labels that each got.

#6 Specify behavior of some program object methods when a device doesn't support online compile/link
  latex/expressingParallelism.tex
Labels: Agenda

#13 Add thread_local keyword to storage class restriction so that can be found with search
  latex/compiler_abi.tex
Labels: Agenda

#22 Fix the order of src/dest in description of explicit memory operations
  latex/sycl_explicit_memory.tex
Labels: Agenda, bug

#2 explicitcopy.cpp example fix, invalid accessor constructor
  latex/code/explicitcopy.cpp
Labels: Agenda, bug

#34 Clarify device_type mapping to OpenCL CL_DEVICE_TYPE responses
  latex/headers/deviceInfo.h
Labels: Batch vote candidate

#35 Clarify device_selector behavior when no devices return a positive score
  latex/programming_interface.tex
Labels: Batch vote candidate

#36 Fix accessor constructors: add allocator as part of buffer type
  latex/accessors.tex
  latex/headers/accessorBuffer.h
Labels: Batch vote candidate

#32 Clarify wording for simple swizzle member functions
  latex/vec_class.tex
Labels: Batch vote candidate

#39 Sub-buffer clarifications
  latex/code/subbuffer.cpp
  latex/programming_interface.tex
Labels: Agenda

#37 Clarify device selector behavior when there is a tie in scoring
  latex/programming_interface.tex
Labels: Batch vote candidate
