Repository KhronosGroup/SYCL-Docs, pull requests merged in 2024-08, with the labels that each got.

#597 Only run CTS issue workflow when opening PRs; run on base branch
  .github/workflows/open_cts_issue.yml
Labels: editorial

#599 Generalize synopsis role
  adoc/config/khronos.css
  adoc/config/synopsis/extension.rb
Labels: editorial

#600 Enable additional API cross-references
  adoc/config/api_xrefs/extension.rb
Labels: editorial

#605 Update for revision 9 release
  README.md
  sycl_version.txt
Labels: editorial

#590 Remove "heterogeneous" where it doesn't make sense
  adoc/chapters/architecture.adoc
Labels: Agenda, editorial

#609 CTS issue workflow: Don't assign PR author to issue
  .github/workflows/open_cts_issue.yml
Labels: Agenda

#607 Fix spelling
  adoc/chapters/programming_interface.adoc
Labels: editorial

#610 Prepare for next SYCL spec major release
  adoc/Makefile
  sycl_version.txt
Labels: editorial
