Repository KhronosGroup/SYCL-Docs, pull requests merged in 2025-01, with the labels that each got.

#691 Change KHR name to lower case
  adoc/extensions/sycl_khr_default_context.adoc
Labels: editorial

#692 Prepare sycl_khr_default_context for publication
  adoc/Makefile
  adoc/extensions/index.adoc
  adoc/extensions/sycl_khr_default_context.adoc
  adoc/scripts/verify_reflow_conformance.sh
  adoc/syclbase.adoc
Labels: Agenda

#634 Redefine SYCL_LANGUAGE_VERSION
  adoc/chapters/device_compiler.adoc
  sycl_version.txt
Labels: Agenda

#625 Clarify and deprecate "execution_capabilities"
  adoc/chapters/programming_interface.adoc
  adoc/config/api_xrefs.adoc
Labels: Agenda

#688 Add pointer-to-object to list of `atomic_ref` types
  adoc/chapters/programming_interface.adoc
Labels: bug

#701 Fix 2 kernel in submit in code example
  adoc/code/mykernel.cpp
Labels: editorial

#623 Clarify default context behavior
  adoc/chapters/programming_interface.adoc
Labels: Waiting for CTS
