Repository KhronosGroup/SYCL-Docs, pull requests merged in 2025-08, with the labels that each got.

#891 Fix `compare_exchange_*` with only one `memory_order`
  adoc/chapters/programming_interface.adoc
Labels: bug, memory model

#850 Clarify accumulator type for reductions and scans
  adoc/chapters/programming_interface.adoc
Labels: clarification

#824 Change buffer API descriptions to use new style
  adoc/chapters/programming_interface.adoc
  adoc/headers/buffer.h
Labels: Agenda

#906 Fix very minor typo
  adoc/chapters/glossary.adoc
Labels: editorial

#907 Fix very minor typo
  adoc/chapters/glossary.adoc
Labels: editorial
