Repository KhronosGroup/SYCL-Docs, pull requests merged in 2025-06, with the labels that each got.

#840 Fix horizontal line
  adoc/chapters/programming_interface.adoc
Labels: editorial

#839 [Editorial] Add "khr" to paragraph titles
  adoc/extensions/sycl_khr_group_interface.adoc
Labels: editorial

#834 Add missing deprecation comments
  adoc/headers/deviceInfo.h
Labels: editorial, deprecated feature

#846 Add missing comment
  adoc/headers/deviceInfo.h
Labels: editorial

#848 Clarify synchronization behavior of sycl::free
  adoc/chapters/programming_interface.adoc
Labels: clarification

#832 Clarify availability of sycl::byte/half on host
  adoc/chapters/programming_interface.adoc
Labels: editorial, clarification

#833 Deprecate the `half_precision::` namespace
  adoc/chapters/programming_interface.adoc
Labels: enhancement
