Repository KhronosGroup/SYCL-Docs, pull requests merged in 2025-07, with the labels that each got.

#867 Add missing deprecation comments
  adoc/headers/deviceInfo.h
Labels: editorial

#873 Update to the latest Docker image
  .github/workflows/CI.yml
Labels: editorial

#829 Rename TagT to DeductionTagT
  adoc/chapters/programming_interface.adoc
  adoc/headers/accessorBuffer.h
  adoc/headers/accessorHost.h
Labels: editorial

#854 Clarify the max_num_sub_groups queries
  adoc/chapters/programming_interface.adoc
Labels: editorial, clarification

#875 Add `host_task` to handler synopsis
  adoc/headers/commandGroupHandler.h
Labels: editorial

#877 Remove "default" from common by-value semantics
  adoc/chapters/programming_interface.adoc
Labels: editorial

#879 Deprecate `accessor::max_size()`
  adoc/chapters/programming_interface.adoc
  adoc/headers/accessorBuffer.h
  adoc/headers/accessorHost.h
  adoc/headers/accessorLocal.h
Labels: deprecated feature

#884 Add SYCL 2020 (Revision 10) to issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/clarification_request.yml
Labels: editorial

#890 Add SYCL 2020 (Revision 10) to issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/clarification_request.yml
Labels: editorial
