Repository KhronosGroup/SYCL-Docs, pull requests merged in 2025-03, with the labels that each got.

#740 Clarify `is_available`
  adoc/chapters/programming_interface.adoc
Labels: clarification

#755 Remove "implementation note"
  adoc/chapters/programming_interface.adoc
Labels: editorial

#729 Minor improvements to Section 4.5 and Appendix A
  adoc/chapters/information_descriptors.adoc
  adoc/chapters/programming_interface.adoc
  adoc/headers/deviceInfo.h
Labels: editorial

#737 Fix reference to rule of five in common-byval.h
  adoc/headers/common-byval.h
Labels: editorial

#738 Remove minimum max_mem_alloc_size
  adoc/chapters/programming_interface.adoc
Labels: bug

#758 Fix description of `sycl::free`
  adoc/chapters/programming_interface.adoc
Labels: bug

#754 Remove references to `compile`/`build_with_source`
  adoc/chapters/opencl_backend.adoc
Labels: bug, Agenda
