Repository KhronosGroup/SYCL-Docs, pull requests merged in 2025-02, with the labels that each got.

#717 Replace "inverse sqrt" with "reciprocal" sqrt
  adoc/chapters/programming_interface.adoc
Labels: editorial

#716 Fix definition of marray::size()
  adoc/chapters/programming_interface.adoc
Labels: bug

#714 Remove reference to OpenCL 1.2 memory model
  adoc/chapters/architecture.adoc
Labels: editorial

#715 Highlight variable templates for known_identity
  adoc/chapters/programming_interface.adoc
Labels: editorial

#709 Add/Run/CI Clang-format on adoc/code
  .clang-format
  .github/workflows/CI.yml
  adoc/code/algorithms.cpp
  adoc/code/anatomy.cpp
  adoc/code/aspectTraitExample.cpp
  adoc/code/basicParallelForItem.cpp
  adoc/code/basicparallelfor.cpp
  adoc/code/bundle-builtin-kernel.cpp
  adoc/code/bundle-kernel-introspection.cpp
  adoc/code/bundle-pre-compile.cpp
  adoc/code/bundle-spec-constants.cpp
  adoc/code/deviceHas.cpp
  adoc/code/explicitcopy.cpp
  adoc/code/lambdaNameExamples.cpp
  adoc/code/largesample.cpp
  adoc/code/myfunctor.cpp
  adoc/code/parallelForWithKernelHandler.cpp
  adoc/code/parallelForWorkGroupWithKernelHandler.cpp
  adoc/code/parallelfor.cpp
  adoc/code/parallelforworkgroup.cpp
  adoc/code/propertyExample.cpp
  adoc/code/queueShortcuts.cpp
  adoc/code/reduction.cpp
  adoc/code/specialization_id.cpp
  adoc/code/subbuffer.cpp
  adoc/code/swizzle-example.cpp
  adoc/code/sycl-external.cpp
  adoc/code/twoOptionalFeatures.cpp
  adoc/code/usingSpecConstants.cpp
  adoc/code/usm_device.cpp
  adoc/code/usm_shared.cpp
  adoc/scripts/clang-format-diff.py
Labels: editorial

#727 Clarify the meaning of different device types
  adoc/chapters/programming_interface.adoc
Labels: editorial

#719 Clarify that RandomFiller uses one random number
  adoc/chapters/programming_interface.adoc
  adoc/code/myfunctor.cpp
Labels: editorial

#718 Fix incorrect reference to vec::as
  adoc/chapters/programming_interface.adoc
Labels: bug, editorial

#743 First draft of process documentation
  README_PROCESS.md
Labels: editorial
